### PR TITLE
OCM-6449 | fix: Changed proxy related fucntion

### PR DESCRIPTION
**Pull request by yingzhanredhat**
https://privatebin.corp.redhat.com/?f2ccee0cf4bdf3f4#AMKSuyKJGgtQhqGA7y8DDgkBFJGvKrSoHBt7vy7AHSAc

### CODE REVIEW

**Comment by yingzhanredhat** [comment]
@hunterkepley Would you help review it?Thanks

**Comment by hunterkepley** [comment]
apologies - i get so many github notifications that I tend to only check slack/jira for updates, approved

**Comment by yingzhanredhat** [comment]
create a  new PR

**Pull request closed without merging**
